name: "Test Deepbits Scan Action"

permissions:
  contents: write

on:
  pull_request:
  push:
    branches:
      - main
      - "RD-1203"
      - "releases/*"

jobs:
  deepbits-scan:
    runs-on: ubuntu-latest
    outputs:
      SCAN_BADGE: ${{ steps.deepbits-scan.outputs.DEEPBITS_BADGE }}
      DEEPSCA_BRANCH_LINK: ${{ steps.deepbits-scan.outputs.DEEPSCA_BRANCH }}
    steps:
      - uses: actions/checkout@v3

      - uses: ./
        id: deepbits-scan

  comment-on-commit:
    needs: deepbits-scan
    runs-on: ubuntu-latest
    steps:
      - name: Create commit comment
        uses: peter-evans/commit-comment@v2
        with:
          body: |
            Scan finished. Click [here](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}#artifacts) to see the results.

            ---

            Powered by [**Deepbits**](https://deepbits.com):
            - Scan Details: ${{ needs.deepbits-scan.outputs.DEEPSCA_BRANCH_LINK }}
            - Badge: ${{ needs.deepbits-scan.outputs.SCAN_BADGE }}

  download-artifact:
    needs: deepbits-scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/download-artifact@v3
        with:
          name: DEEPBITS_SCAN_RESULTS

      - name: Display structure of downloaded files
        run: ls -R
